//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trivia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int score_id { get; set; }
        public string player { get; set; }
        public Nullable<int> time { get; set; }
    }
}
